#!/usr/bin/env bash
#
# This is the main script which handles jenkins builds of ApsimX.
# This script will run a script specified by first argument inside
# an apsimng-build docker image. The script must be located
# inside the container-scripts directory.
#
# Additionally, the PULL_ID variable must be set before running
# this script.
set -e

# Sometimes PULL_ID variable is not set by jenkins
# and we need to use ghprbPullId. This seems to occur
# after a manual retest.
test -z ${PULL_ID:+x} && PULL_ID=$ghprbPullId
test -z ${PULL_ID:+x} && ( echo "PULL_ID not set"; exit 1 )
test -z ${COMMIT_AUTHOR:+x} && COMMIT_AUTHOR=$ghprbActualCommitAuthor
test -z ${MERGE_COMMIT} && MERGE_COMMIT=$sha1
test -z ${GITHUB_PAT:+x} && ( echo "GITHUB_PAT not set"; exit 1 )

# Note: we don't exit early if COMMIT_AUTHOR isn't set. We can get that
# from the git logs, but not until we've cloned the repo.

# Ensure that the author of the pull request has referenced an issue.
url="https://api.github.com/repos/APSIMInitiative/ApsimX/pulls/$PULL_ID"
json=$(curl -s "$url")
body=$(echo "$json" | jq --raw-output ".body")
echo "$body" | grep -iE '(resolves|working on) #[0-9]+' || (
    echo "PR #$PULL_ID does not reference an issue. You will need to edit the initial PR comment and add 'Working on #xxxx' or 'Resolves #xxxx'."
    echo "You will then need to rerun the test suite. To do this, add another comment on the pull request containing the text 'retest this please jenkins'."
    echo "See https://apsimnextgeneration.netlify.app/contribute/sourcetree/pushandpullrequest/ for more details."
    echo body=$body
    echo json=$json
    exit 1
)

export PULL_ID COMMIT_AUTHOR

if [ $# -lt 1 ]
then
    echo $0: Expected at least 1 argument - should be a command to run inside docker container
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

container=apsiminitiative/apsimng-build
docker pull -q $container

docker --version

echo Running docker container $container with argument ${@:2}
docker run --rm --entrypoint=$1 -v "$DIR/container-scripts":/container-scripts -w /container-scripts -e BUILDS_JWT -e APSIM_NO_DOCKER=1 -e MERGE_COMMIT -e PULL_ID -e COMMIT_AUTHOR -e SOYBEAN_PASSWORD -e NPI_PASSWORD -e CORNSOY_PASSWORD -e SWIM_PASSWORD -e TESTDB -e NEWDB -e OLDDB -e CollectorURL -e POSTATS_UPLOAD_URL -e CHANGE_DB_CREDS_PSW -e NETLIFY_BUILD_HOOK $container "${@:2}"
