#!/usr/bin/env bash
#
# This script deploys an ApsimX release, causing this version to start
# appearing in the upgrade lists.
#
# This script requires that the following variables are set:
# - PULL_ID         ID of the pull request which triggered this release
# - CHANGE_DB_CREDS_PSW     Token to update builds DB
# - NETLIFY_BUILD_HOOK      Token to trigger a netlify build
# this script.

set -euo pipefail

test -z ${PULL_ID:+x} && ( echo "PULL_ID not set"; exit 1 )
test -z ${CHANGE_DB_CREDS_PSW:+x} && ( echo "CHANGE_DB_CREDS_PSW not set"; exit 1 )
test -z ${NETLIFY_BUILD_HOOK:+x} && ( echo "NETLIFY_BUILD_HOOK not set"; exit 1 )

curl --fail-with-body -s "https://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/AddBuild?pullRequestNumber=$PULL_ID&ChangeDBPassword=$CHANGE_DB_CREDS_PSW"
curl --fail-with-body -s "https://registration.apsim.info/api/updateproducts"
curl --fail-with-body -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK
