#!/usr/bin/env bash
#
# This is run inside a docker container and handles tasks
# common to all build stages:
# - Clones apsim
# - Builds apsim
#
# Note that this script does not change the working directory.

set -e

export apsimx="/tmp/ApsimX"
git clone --quiet https://github.com/APSIMInitiative/ApsimX "$apsimx"

pushd "$apsimx"
git fetch origin +refs/pull/$PULL_ID/*:refs/remotes/origin/pr/$PULL_ID/*
git checkout origin/pr/$PULL_ID/merge
FrameworkPathOverride=/usr/lib/mono/4.7.2-api/ dotnet build -v m --nologo -c Release ApsimX.sln
popd
