#!/usr/bin/env bash
set -euo pipefail

# Clone and build apsim
. ./main
echo Retrieving version info...
version=$(./get-revision $PULL_ID)
year=$(TZ=Australia/Brisbane date +%-Y)
month=$(TZ=Australia/Brisbane date +%-m)
full_version=$year.$month.$version.0

cd "$apsimx"

sed -i -e "s/0\.0\.0\.0/$full_version/g" "$apsimx/Models/Properties/AssemblyVersion.cs"
dotnet build -c Release ApsimX.sln

# Extract password-protected datasets.
soybean=Tests/Validation/Soybean
wheat=Tests/Validation/Wheat
cornsoy=Tests/Validation/System/FACTS_CornSoy
7z -p$SOYBEAN_PASSWORD x $soybean/ObservedFACTS.7z -o$soybean
7z -p$NPI_PASSWORD x $wheat/NPIValidation.7z -o$wheat
7z -p$CORNSOY_PASSWORD x $cornsoy/FACTS_CornSoy.7z -o$cornsoy

# Run all .apsimx files outside of ./Tests and ./ApsimNG
find . -not \( -path ./Tests/UnitTests -prune \) -not \( -path ./ApsimNG -prune \)  -name '*.apsimx' -print0 | xargs -0 dotnet bin/Release/netcoreapp3.1/Models.dll --verbose --run-tests

# Get date in yyyy.M.d-HH:mm format
TIMESTAMP=`date +%Y.%-m.%-d-%H:%M`

test -z ${COMMIT_AUTHOR:+x} && COMMIT_AUTHOR="$(git log -1 --pretty=%an)"

# Run P/O stats collector
cd ..
git clone https://github.com/APSIMInitiative/APSIM.PerformanceTests APSIM.PerformanceTests
cd APSIM.PerformanceTests
git checkout refactor
collector=APSIM.POStats.Collector
dotnet build -v m -c Release $collector/$collector.csproj
dotnet $collector/bin/Release/netcoreapp3.1/$collector.dll "$PULL_ID" "$TIMESTAMP" "$COMMIT_AUTHOR" "$apsimx/Tests/Validation" "$apsimx/Tests/UnderReview"

# Build Autodocs
autodocs=APSIM.Documentation
cd "$apsimx"
if [[ -d $autodocs ]]
then
    # This will generate autodocs to $apsimx/autodocs
    output="$PWD/documents"
    bin/Release/netcoreapp3.1/APSIM.Documentation $output
    for f in $output/*
    do
        curl -fX POST -H "Authorization: bearer $BUILDS_JWT" -F "file=@$f" "https://builds.apsim.info/api/nextgen/upload/docs?pullRequestNumber=$PULL_ID"
    done
    echo "Autodocs successfully generated and uploaded."
fi
